// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool to work around XAML compiler issues
//      with .NET 10 and Windows App SDK 1.7 in Release mode.
//
//      与 XamlCompiler 自动生成的 App.g.cs / App.g.i.cs 互补：
//      - csproj 对 Windows Release TFM 定义了 DISABLE_XAML_GENERATED_MAIN，
//        自动生成的 Program 部分会被跳过，由本文件的 Program 提供（入口点兜底）。
//      - App 类（_contentLoaded / InitializeComponent）由 XamlCompiler 生成的
//        App.g.i.cs 无条件提供（实测 Release 下该文件同样参与编译，output.json
//        的 GeneratedCodeFiles 为空并不代表代码缺失），本文件不再重复定义，
//        避免 CS0102/CS0111 重复成员。
//      - 若 XamlCompiler 极端情况下未产出 App.g.i.cs，由 csproj 中的
//        EnsureAppInitializeComponent target 动态引入
//        App.InitializeComponent.fallback.cs 兜底，见 csproj 说明。
//      - Debug 模式下 XamlCompiler 正常生成代码，本文件由 csproj 排除（Compile Remove），
//        避免 CS0111 重复成员。
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CatClawMusic.Maui.WinUI
{
#if DISABLE_XAML_GENERATED_MAIN
    /// <summary>
    /// Program class
    /// </summary>
    public static class Program
    {
        [global::System.STAThreadAttribute]
        static void Main(string[] args)
        {
            global::WinRT.ComWrappersSupport.InitializeComWrappers();
            global::Microsoft.UI.Xaml.Application.Start((p) => {
                var context = new global::Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(global::Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread());
                global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
                new App();
            });
        }
    }
#endif
}
